### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by mariamquesada** [TCD-SWENG-Group-18-2024/CodeCraft#10]
Some of us are currently unable to run on http://localhost:8080/llm and instead have to run on http://127.0.0.1:8080/llm.

**Comment by luciabrown** [comment]
Both appear to be working now for myself and Paddy @mariamquesada
Can this be tested again and closed if not an issue anymore?

**Comment by luciabrown** [comment]
Also, localhost is not specified when you run codecraft.py. See image. 
![image](https://github.com/TCD-SWENG-Group-18-2024/CodeCraft/assets/128033551/f7b4f4eb-9fcf-4e0b-9e3f-01d4d596650f)
Was localhost previously appearing in the terminal when running backend? Is there any issue with continuing using the 127.0.0.1:8080 ?
