### ISSUE TITLE
error with vector db tutorial - milvus time out error

### ISSUE THREAD

**Issue by bfeeney6** [TCD-SWENG-Group-18-2024/CodeCraft#118]

**Comment by bfeeney6** [comment]
theres a file vectordbtrial.py in the backend branch that contains the contents of the code from the tutorial. I have been trying to get this working locally on my own laptop. I created my own virtual enviornment and .env file with the open ai key but when i run the code it gives me a milvus timeout error which im not sure how to fix

**Comment by luciabrown** [comment]
This is resolved as confirmed by Gerard
