### ISSUE TITLE
LLM Response of "I cannot view previous messages"

### ISSUE THREAD

**Issue by luciabrown** [TCD-SWENG-Group-18-2024/CodeCraft#136]
Due to bad prompting. 
LLM’s memory works by searching for similar or relevant previous messages. 
A prompt along the lines of “what did I just say?” won’t make the LLM return anything meaningful. 
Regardless, LLM should not be saying “No, I can’t do that” and instead admit that it searches based on similarities

**Comment by FinnStrike** [comment]
Vector Database is now implemented
